.Dd June 25, 2026
.Dt WTCDBEXPORT 1
.Os
.Sh NAME
.Nm wtcdbexport
.Nd exports items stored in a Windows Explorer thumbnail cache database \
(thumbcache.db) file
.Sh SYNOPSIS
.Nm wtcdbexport
.Op Fl l Ar logfile
.Op Fl t Ar target
.Op Fl hvV
.Ar source
.Sh DESCRIPTION
.Nm wtcdbexport
is a utility to export items stored in a Windows Explorer thumbnail cache \
database (thumbcache.db) file
.Pp
.Nm wtcdbexport
is part of the
.Nm libwtcdb
package.
.Nm libwtcdb
is a library to access the Windows Explorer thumbnail cache database (WTCDB) \
format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl l Ar logfile
specify the file in which to log information about the exported items
.It Fl t Ar target
specify the target directory to export to (default is the source filename \
followed by .export)
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# wtcdbexport thumbcache_32.db
wtcdbexport 20260625
.sp
Opening file.
Export completed.
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh SEE ALSO
.Xr wtcdbinfo 1
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libwtcdb/issues
.Sh COPYRIGHT
Copyright (C) 2010-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
